export const products = [
    {
        id: 1,
        productName: 'Засіб для килимів',
        count: 0,
        selected: false,
        price: 300,
        volume: '1000 мл',
        img: 'img-product-carpet-cleaner.png',
    },
    {
        id: 2,
        productName: 'Засіб для меблів',
        count: 0,
        selected: false,
        price: 250,
        volume: '500 мл',
        img: 'img-product-furniture-cleaner.png',
    },
    {
        id: 3,
        productName: 'Набір для очищення меблів та килимів',
        count: 0,
        selected: false,
        price: 550,
        discountPrice: 500,
        volume: '1000 мл та 500 мл',
        img: 'img-product-set.png',
    },
];
