export const products = [
    {
        id: 1,
        productName: 'Миючий засіб для килимів,',
        productShortName: 'Засіб для килимів',
        count: 0,
        selected: false,
        price: 699,
        discountPrice: 649,
        volume: '1000 мл',
        img: 'img-product-carpet-cleaner.png',
        btnName: 'Замовити засіб для килимів',
    },
    {
        id: 2,
        productName: 'Засіб для чищення меблів,',
        productShortName: 'Засіб для меблів',
        count: 0,
        selected: false,
        price: 459,
        discountPrice: 399,
        volume: '500 мл',
        img: 'img-product-furniture-cleaner.png',
        btnName: 'Замовити засіб для меблів',
    },
    {
        id: 3,
        productName: 'Набір для очищення меблів та килимів',
        productShortName: 'Набір для очищення меблів та килимів',
        count: 0,
        selected: false,
        price: 1049,
        discountPrice: 949,
        volume: '1000 мл та 500 мл',
        img: 'img-product-set.png',
        btnName: 'Замовити набір зі знижкою',
    },
];
